// Compatibility Re-exports pointing to new Physical Module paths
export {
  CandidateIQDashboard,
  CandidateDashboard,
  MatchedRequisitions,
  CandidateIQProfile,
  DynamicProfileRenderer,
  ManualProfileBuilder,
  ProfileDraftEditor,
  ProfileEvidenceIntelligence,
  SkillIntelligence,
  TechnicalSkillIntelligence,
  SkillGapIntelligence,
  ATSScoreGauge,
  ResumeParserIQModal,
  ProfileReplacementModal,
  ScoreExplanationModal,
  ResumeIntelligence,
  ResumeUploader,
  PdfDocumentViewer,
  ResumeDetailWorkspace,
  ResumeHistory,
  ProfileReviewHub,
  JobDiscovery,
  JobTrackerView,
  JobDetailsView,
  JobMatchingView,
  ApplicationTracker,
  ApplicationModal,
  CandidateActivityHub,
  ActivityPracticeRoom
} from '../../modules/candidate';
